server:
  port: 8989
  context-path: /AppDemo
  jsp-servlet:
    init-parameters:
      development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jps
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: hr
    password: hr
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
